<%@ Page Language="VB" AutoEventWireup="false" CodeBehind="Cortes.aspx.vb" Inherits="Tesch_Pos_web.Cortes" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" />
    <link rel="stylesheet" type="text/css" href="Vendor/css/google.prettify.min.css" />
    <telerik:RadStyleSheetManager id="RadStyleSheetManager1" runat="server" />
</head>
<body>
    <form id="form1" runat="server">
        <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
            <Scripts>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js" />
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js" />
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js" />
            </Scripts>
        </telerik:RadScriptManager>
        <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/3.2.0/anchor.js"></script>
        <script src="bootbox.js"></script>
        <script src="Vendor/js/prettify.min.js"></script>
        <script src="Vendor/js/jquery.scrollUp.min.js"></script>
        <script src="js/example.js"></script>
        <script src="js/demos.js"></script>
        <script src="js/index.js"></script>
        <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
        </telerik:RadAjaxManager>
        <telerik:RadAjaxLoadingPanel EnableAjaxSkinRendering="true" ID="RadAjaxLoadingPanel1" runat="server">
        </telerik:RadAjaxLoadingPanel>
        <telerik:RadAjaxPanel ID="RadAjaxPanel1" LoadingPanelID="RadAjaxLoadingPanel1" ShowLoadingPanelForPostBackControls="true" runat="server" Height="100%" Width="100%">
            <telerik:RadGrid ID="grdCorte" ClientSettings-Virtualization-LoadingPanelID="RadAjaxLoadingPanel1" runat="server" Skin="Bootstrap"
                AutoGenerateColumns="True" Culture="es-ES" Font-Size="Small" MasterTableView-CommandItemSettings-ShowAddNewRecordButton="False"
                DataSourceID="SQLCorte" IsExporting="False" AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false"
                AllowAutomaticUpdates="true"
                AllowAutomaticInserts="true"
                AllowAutomaticDeletes="true">
                <GroupingSettings CollapseAllTooltip="Collapse all groups" />
                <MasterTableView CanRetrieveAllData="true" AllowPaging="true" PagerStyle-PageSizes="10" DataSourceID="SQLCorte" CommandItemSettings-AddNewRecordText="Añadir plantilla" CommandItemDisplay="Top">
                </MasterTableView>
                <SelectedItemStyle BorderStyle="Groove" />
            </telerik:RadGrid>
        </telerik:RadAjaxPanel>

        <asp:SqlDataSource runat="server" ID="SQLCorte" ConnectionString='<%$ ConnectionStrings:TESCH_POS %>'
            SelectCommand="exec [CortesAbiertos] @Session">
            <SelectParameters>
                <asp:SessionParameter SessionField="Session" Name="Session" />
            </SelectParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
